### ISSUE TITLE
Does http://demo.anavi.technology/ really support Anavi Thermometer?

### ISSUE THREAD

**Issue by cederlys** [AnaviTechnology/anavi-docs#16]
https://github.com/AnaviTechnology/anavi-docs/blob/master/anavi-thermometer/anavi-thermometer.md claims:

> To verify that ANAVI Thermometer is up and running open a modern web browser and visit demo.anavi.technology. Enter your machine ID.

But when I do that, I only get a website for the ANAVI Light Controller.  Should all references to the demo website be removed from the ANAVI Thermometer documentation, or will the website soon be updated to support the Thermometer as well?

**Comment by leon-anavi** [comment]
Hi @cederlys,

Thanks for reporting this issue. Other people have also complained about it so I have just updated demo.anavi.technology:  https://github.com/AnaviTechnology/anavi-light-demo/commit/828f4cd689f0559b3fa1b0e573ebeb0aaf194dd2

Now it shows the temperature and the humidity reported from ANAVI Thermometer as on the screenshot below:
![demo](https://user-images.githubusercontent.com/3279083/57957766-16c0a780-7906-11e9-9a06-e3f359c43266.png)

My plans is over the time to improve demo.anavi.technology and to show different UI depending on the type of the connected board.

Thanks, Leon
