### ISSUE TITLE
Error building BMP180

### ISSUE THREAD

**Issue by gtodd876** [AnaviTechnology/anavi-docs#45]
I was able to compile BH1750 & HTU21D but I'm having an issue with BMP180

<img width="1216" alt="Screen Shot 2022-02-17 at 10 09 08 AM" src="https://user-images.githubusercontent.com/28220658/154510401-c421de93-2e1a-4705-857e-14e8570faaa7.png">

It's as if this include guard in `BMP180.h` isn't working?
`#ifndef _BMP180_H_`

I'm using:
 * i2c-tools 4.2-1+b1
 * python3-rpi.gpio 0.7.0-0.2+b1
 * wiringpi 2.52

My Raspberry Pi is a 4 Model B Rev 1.2
running Raspbian GNU/Linux 11 (bullseye)

The `ld` linker logging the errors is version 2.35.2
 
 Thank you in advance if anybody can help point me in the right direction!

**Comment by leon-anavi** [comment]
Hi @gtodd876,

Thank you for reporting this issue and sorry for the inconvenience. After a lot of turmoil recently [library wiringpi was deprecated (probably for good)](http://wiringpi.com/wiringpi-deprecated/) in latest releases of Raspberry Pi OS this affects some of the examples. We will need to move away from wiringpi. Let's keep this issue open until it is done.

Best regards,
Leon

**Comment by gtodd876** [comment]
No problem at all! Sounds great. Thank you for the information and I will research alternatives in the meantime.

**Comment by gtodd876** [comment]
So far I've dug up these possible alternatives:
* [BCM2835](https://www.airspayce.com/mikem/bcm2835/)
* [Pigpio](https://abyz.me.uk/rpi/pigpio/)
* [Unofficial Mirror/Prot of WiringPi](https://github.com/WiringPi/WiringPi)

**Comment by leon-anavi** [comment]
Hi @gtodd876,

I have added a Python3 script as an example for reading temperature and barometric pressure from BMP180 using smbus:
https://github.com/AnaviTechnology/anavi-examples/blob/master/sensors/BMP180/python/BMP180.py

Best regards,
Leon

**Comment by gtodd876** [comment]
Thank you so much Leon!! Can't wait to use this!
